name: Android

on:
  push:
    branches:
      - master

jobs:
  build:
    name: libprotobuf-lite
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Run sdkmanager update
        run:  ${ANDROID_HOME}/tools/bin/sdkmanager --update
      - name: Install android platform, platform-tools, build-tools and ndk
        run:  ${ANDROID_HOME}/tools/bin/sdkmanager --install "cmdline-tools;latest" "platform-tools" "platforms;android-33" "build-tools;33.0.0" "ndk;23.1.7779620"
      - name: Setup NDK path
        run: echo "ANDROID_NDK_ROOT=${ANDROID_HOME}/ndk/23.1.7779620/" >> $GITHUB_ENV
      - name: Build project
        run:
          ./build.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: libprotobuf-lite
          path: |
            obj/local/x86/libprotobuf-lite.a
            obj/local/x86_64/libprotobuf-lite.a
            obj/local/armeabi-v7a/libprotobuf-lite.a
            obj/local/arm64-v8a/libprotobuf-lite.a
            obj/local/include/
